export const manualYesterdayBrands = [
  "Himali Great Foods",
  "China Garten",
  "Maa Ki Rasoi",
  "Murthal Waala",
  "Khichdi Desi Ghee Wali",
  "Khichdi Maker",
  "Mahadev ke special chole bhature",
  "Mahadev Ka Dhaba",
  "Dwarka Dhaba",
  "Dwarka Food Cafe",
  "Gulati Ji Ke Special Chole Bhature",
  "Sita Ram Ji Ke Special Chole Bhature",
  "Mamta Ka Dhaba",
  "Janta Cafe",
  "Benaam Badshah Food",
  "Taste Of Dwarka",
  "Mata Ji Ka Dhaba",
  "Bindaas Cafe Or Dhaba",
  "Bhojanalya",
  "Dhaba King",
  "Nagpal bhature wale di hatti",
  "Kitchen King",
  "Fitness Health",
  "Guntur chitti idly(2)",
  "biriyani blittz (3)",
  "rrb ambur biriyani",
  "Keralapura Hindu Milatry Hotel",
  "Magadhi Mewa Sweets & Chaats",
  "Aarushi Darjeeling Hot Momos",
  "Sri Manjunatha Tandoori Corner",
  "Combo Meals",
  "Bezawada Adda",
  "Curry Point",
  "Calcutta Curry",
  "Mandi Handi",
  "Murgan cafe"
]
